export const GET_PENDING_TASKS_FOR_PINCODE = 'GET_PENDING_TASKS_FOR_PINCODE';
export const GET_ASSIGNED_TASKS = 'GET_ASSIGNED_TASKS';
export const GET_CREATED_TASKS = 'GET_CREATED_TASKS';
export const TAKE_ACTION_ON_TASK = 'TAKE_ACTION_ON_TASK';
export const REGISTER_USER_TASK = 'REGISTER_USER_TASK';